{
    "name": "Makersbrain Commercial Operations",
    "summary": "Plan markets and site obligations, travel costs, and profitability.",
    "version": "19.0.2.2.0",
    "license": "LGPL-3",
    "category": "Services/Project",
    "author": "Makersbrain",
    "depends": ["account", "project", "hr_timesheet"],
    "data": [
        "security/mb_commercial_operations_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/ir_cron.xml",
        "views/res_config_settings_views.xml",
        "views/project_views.xml",
        "views/commercial_contract_views.xml",
        "views/commercial_operation_views.xml",
        "views/travel_estimate_views.xml",
        "views/commercial_profitability_views.xml",
        "views/commercial_planning_views.xml",
        "views/profitability_report_views.xml",
        "views/mb_commercial_operations_menus.xml",
        "reports/commercial_operation_report.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
