{
    "name": "MakersBrain Label Studio",
    "summary": "Design, version, render and print product and piece labels.",
    "description": "Versioned thermal-label design and product/lot printing.",
    "version": "19.0.1.2.5",
    "license": "AGPL-3",
    "category": "Inventory/Inventory",
    "author": "MakersBrain",
    "depends": ["product", "stock", "web"],
    "external_dependencies": {
        "python": ["qrcode", "reportlab"],
    },
    "data": [
        "security/mb_label_security.xml",
        "security/ir.model.access.csv",
        "data/mb_label_data.xml",
        "wizard/mb_label_print_wizard_views.xml",
        "views/mb_label_views.xml",
        "views/product_views.xml",
        "views/stock_lot_views.xml",
        "views/mb_label_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "mb_label/static/src/editor/printer_presets.js",
            "mb_label/static/src/editor/selection.js",
            "mb_label/static/src/editor/template_file.js",
            "mb_label/static/src/editor/template_formatters.js",
            "mb_label/static/src/editor/label_editor.js",
            "mb_label/static/src/editor/label_editor.xml",
            "mb_label/static/src/editor/label_editor.scss",
            "mb_label/static/src/printer/printer_registry.js",
            "mb_label/static/src/printer/device_memory.js",
            "mb_label/static/src/printer/raster.js",
            "mb_label/static/src/printer/mb_phomemo/devices.js",
            "mb_label/static/src/printer/mb_phomemo/raster.js",
            "mb_label/static/src/printer/mb_phomemo/phomemo_protocol.js",
            "mb_label/static/src/printer/phomymo/constants.js",
            "mb_label/static/src/printer/phomymo/debug.js",
            "mb_label/static/src/printer/phomymo/ble.js",
            "mb_label/static/src/printer/phomymo/raster.js",
            "mb_label/static/src/printer/phomymo/printer.js",
            "mb_label/static/src/printer/system_adapter.js",
            "mb_label/static/src/printer/phomemo_adapter.js",
            "mb_label/static/src/printer/niimbot_adapter.js",
            "mb_label/static/src/printer/device_print.js",
            "mb_label/static/src/printer/device_print.xml",
            "mb_label/static/src/printer/device_print.scss",
        ],
        "web.assets_unit_tests": [
            "mb_label/static/src/printer/raster.js",
            "mb_label/static/src/printer/printer_registry.js",
            "mb_label/static/src/printer/device_memory.js",
            "mb_label/static/src/printer/phomemo_adapter.js",
            "mb_label/static/src/printer/niimbot_adapter.js",
            "mb_label/static/tests/**/*.test.js",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
