#!/usr/bin/env python3
"""Build the landing page: one self-contained file, no external requests.

    python3 tools/build_landing.py

Reads  landing/index.src.html
Writes landing/index.html

The fonts, `tokens.css` and `ui.css` all come from `@makersbrain/brand` in
node_modules rather than from a copy in this repository. That is the whole point
of the page being generated: it renders with the same stylesheet the control
plane ships, so the marketing site cannot drift from the product it is
advertising without the drift being a version bump anyone can see.

Fonts are inlined as data URIs rather than linked because the page has to work
as a single file -- deploying it is copying one file, and a linked font URL
would fail silently and render the specimen in a fallback face.

This repository owns the marketing page; the shared package owns the design
system and its reference material.
"""

import base64
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAND_ROOT = ROOT
LANDING = ROOT / "landing"

LATIN = (
    "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, "
    "U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, "
    "U+2212, U+2215, U+FEFF, U+FFFD"
)
LATIN_EXT = (
    "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, "
    "U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, "
    "U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF"
)

# family, weight range, package subpath, unicode-range
FACES = [
    ("Bitter", "400 700", "fonts/bitter-latin.woff2", LATIN),
    ("Bitter", "400 700", "fonts/bitter-latinext.woff2", LATIN_EXT),
    ("IBM Plex Sans", "100 700", "fonts/plex-latin.woff2", LATIN),
    ("IBM Plex Sans", "100 700", "fonts/plex-latinext.woff2", LATIN_EXT),
]


def resolve(subpath: str) -> pathlib.Path:
    """Resolve a path inside @makersbrain/brand through its own exports map.

    Node is asked rather than node_modules being walked by hand, so the package
    is free to rearrange its internals without breaking this script.
    """
    script = f'process.stdout.write(require.resolve("@makersbrain/brand/{subpath}"))'
    try:
        out = subprocess.run(
            ["node", "-e", script],
            cwd=BRAND_ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    except subprocess.CalledProcessError:
        sys.exit(
            f"cannot resolve @makersbrain/brand/{subpath}.\nRun `npm ci` in {BRAND_ROOT} first."
        )
    return pathlib.Path(out)


def face_css(family: str, weight: str, subpath: str, urange: str) -> str:
    b64 = base64.b64encode(resolve(subpath).read_bytes()).decode("ascii")
    return (
        "@font-face{"
        f"font-family:'{family}';font-style:normal;font-weight:{weight};"
        "font-display:block;"
        f"src:url(data:font/woff2;base64,{b64}) format('woff2');"
        f"unicode-range:{urange};"
        "}"
    )


def main() -> int:
    src_path = LANDING / "index.src.html"
    src = src_path.read_text()

    for token in ("__FONT_CSS__", "__TOKENS_CSS__", "__UI_CSS__"):
        if token not in src:
            sys.exit(f"{src_path.name} has no {token} placeholder")

    out = src.replace("__FONT_CSS__", "\n".join(face_css(*f) for f in FACES))
    out = out.replace("__TOKENS_CSS__", resolve("tokens.css").read_text())
    out = out.replace("__UI_CSS__", resolve("ui.css").read_text())

    # Stamp the version the page was built against. A marketing page that has
    # silently fallen a major version behind the product looks fine and is
    # wrong, so the answer should be greppable in the artefact itself.
    #
    # Prepended rather than placed in <head>, because this page has no <head>:
    # it is a fragment, wrapped in a document by whatever serves it.
    version = json.loads(resolve("package.json").read_text())["version"]
    out = f"<!-- Generated by tools/build_landing.py. Do not edit; edit index.src.html.\n     Design system: @makersbrain/brand@{version} -->\n{out}"

    dest = LANDING / "index.html"
    dest.write_text(out)
    print(f"wrote {dest.relative_to(ROOT)} ({len(out) // 1024} KB, brand {version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
