#!/usr/bin/env python3
"""Copy the brand stylesheets into the surfaces that consume them.

`brand/` is the source of truth, but Vite's dev server will not serve files
from outside its own root, so the control plane needs its own copy rather than
a relative `@import` that works in a build and fails in `npm run dev`. The
copies are checked in so a clean checkout builds without running this first.

    python3 tools/sync_brand.py           # write the copies
    python3 tools/sync_brand.py --check   # fail if they have drifted

`make check` runs the --check form, so an edit to brand/ that never reached the
control plane is a CI failure rather than a slow visual surprise.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAND = ROOT / "brand"

HEADER = (
    "/* Generated by tools/sync_brand.py from {source}. Do not edit.\n"
    " * Change the source, then run `make brand-sync`. */\n\n"
)

# source in brand/ -> destination
TARGETS = {
    "tokens.css": ROOT / "control-plane/web/src/styles/tokens.css",
    "ui.css": ROOT / "control-plane/web/src/styles/ui.css",
}


def rendered(name: str) -> str:
    return HEADER.format(source=f"brand/{name}") + (BRAND / name).read_text()


def main() -> int:
    check = "--check" in sys.argv
    drifted = []

    for name, dest in TARGETS.items():
        want = rendered(name)
        have = dest.read_text() if dest.exists() else None
        if want == have:
            continue
        if check:
            drifted.append(dest.relative_to(ROOT))
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(want)
        print(f"wrote {dest.relative_to(ROOT)}")

    if drifted:
        print("brand stylesheets are out of sync:", file=sys.stderr)
        for path in drifted:
            print(f"  {path}", file=sys.stderr)
        print("run `make brand-sync`", file=sys.stderr)
        return 1

    if check:
        print("brand stylesheets are in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
